### ISSUE TITLE
IllegalArgumentException without url parameter in @FeignClient in Server Project

### ISSUE THREAD

**Issue by spdeepak** [ryanjbaxter/beginners-guide-to-spring-cloud#2]
Hi,

I am trying to do the same example as in this project. But I am using Spring Boot 2.0.1.RELEASE and Finchley.RELEASE for Spring Cloud.

But if I do not pass the URL parameter for the @FeignClient used on NameFeignClient Interface the endpoints in WebController do not work at all i.e, localhost:8080. But if I do a localhost:8080/greeting or localhost:8080/name or localhost:9090 or localhost:7070 works perfectly fine. I thought url parameter in the @FeignClient is optional as it is supposed to discover from the name parameter.

Am I missing something, or did I do any mistake? Because in your talk I remember you telling that as we are using OpenFeign we can just give the name parameter in the annotation and the name microservice would be discovered by the web microservice.

Exception I get is : nested exception is java.lang.IllegalArgumentException: Expected authority at index 7: http://

**Comment by ryanjbaxter** [comment]
Can you provide the modified sample app so I can take a look?

**Comment by spdeepak** [comment]
Yeah sure. https://github.com/spdeepak/Example/tree/master/Spring-Cloud

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/pull/3136
